CREATE TABLE CADASTRO_USUARIO(
ID_USUARIO INTEGER PRIMARY KEY AUTO_INCREMENT,
T_NOME VARCHAR (30) NOT NULL,
T_EMAIL VARCHAR (30) NOT NULL,
T_SENHA VARCHAR (12) NOT NULL,
T_RSENHA VARCHAR (12) NOT NULL
);

